# Complete front's path (with city's slug)
front:
    path:     /{city}
    defaults: { _controller: TestBundle:Default:front }

# Symple front's path
_front:
    path:     /
    defaults: { _controller: TestBundle:Default:front }

static_page:
    pattern:  /sitio/{page}
    defaults: { _controller: TestBundle:Default:static}

change_city:
    pattern: /city/change-to-{city}
    defaults: { _controller: TestBundle:Default:change }
