front:
    path:     /
    defaults: { _controller: TestBundle:Default:front }

static_page:
    path:     /sitio/help
    defaults: { _controller: TestBundle:Default:help}

static_page:
    path:     /sitio/contact
    defaults: { _controller: TestBundle:Default:contact}

day_offer:
    path:     /dayoffer
    defaults: { _controller: TestBundle:Default:dayoffer}

