# Complete front's path (with city's slug)
#front:
#    path:     /{city}
#    defaults: { _controller: TestBundle:Default:front }

# Symple front's path
#_front:
#    path:     /
#    defaults: { _controller: TestBundle:Default:front }

static_page:
    pattern:  /sitio/{page}
    defaults: { _controller: TestBundle:Default:static}

change_city:
    pattern: /city/change-to-{city}
    defaults: { _controller: TestBundle:Default:change }

offer:
    pattern: /{city}/offers/{slug}
    defaults: { _controller: TestBundle:Default:offer }

recent_cities:
    pattern: /{city}/recent
    defaults: { _controller: TestBundle:Default:recent }

front_shop:
    pattern: /{city}/shops/{shop}
    defaults: { _controller: TestBundle:Default:front }

user_shopping:
    pattern: /shopping
    defaults: {_controller: TestBundle:Default:shopping}