test_homepage:
    path:     /
    defaults: { _controller: TestBundle:Default:index }

test_services:
    path:     /servicios
    defaults: { _controller: TestBundle:Default:services }

test_contactos:
    path:     /contactos
    defaults: { _controller: TestBundle:Default:contactos }

test_proyectos:
    path:     /proyectos
    defaults: { _controller: TestBundle:Default:proyectos }

test_base:
    path:     /base
    defaults: { _controller: TestBundle:Default:base }

test_filla:
    path:     /filla
    defaults: { _controller: TestBundle:Default:filla }

test_productos:
    path:     /productos
    defaults: { _controller: TestBundle:Default:productos }