front:
    path:     /
    defaults: { _controller: TestBundle:Default:front }

static_page:
    pattern:  /sitio/{page}
    defaults: { _controller: TestBundle:Default:static}

day_offer:
    path:     /dayoffer
    defaults: { _controller: TestBundle:Default:dayoffer}

